### ISSUE TITLE
Code quits while it faces an error

### ISSUE THREAD

**Issue by Philotheephilix** [Philotheephilix/Multi-funtional-telegram-bot#1]
Code quits while it faces an error but bot should just skip those and continue working
like when weather is asked by the user with wrong spelling it just crashes
fix needed
1. usage of exception handling
2. adding infinity poll

**Comment by Philotheephilix** [comment]
Initially fixed by configuring **bot to poll infinitively** whatever the error is

**Comment by Philotheephilix** [comment]
mail checker code quit will be fixed in v1.1

**Comment by KABILANSRK** [comment]
Issue CLOSED by this [commit](https://github.com/Philotheephilix/Multi-funtional-telegram-bot/commit/3937507ed6dc3974717ab75f88fb0ac5e04a3fb0)
