### ISSUE TITLE
junk data removal (converted pdf's)

### ISSUE THREAD

**Issue by KABILANSRK** [Philotheephilix/Multi-funtional-telegram-bot#2]
while converting jpg to pdf, The image files received and temporary pdf binary files and merged pdf file remains in the disk
removal of these junk files is mandatory to ensure user privacy and avoid data leaks

**Comment by Philotheephilix** [comment]
Will work on it together and fix it this week :)

**Comment by Philotheephilix** [comment]
Fixed junk stayback with this commit [Junk Removal](https://github.com/Philotheephilix/Multi-funtional-telegram-bot/commit/c1306505a93bfb6ccfe7bdff0ca07a63ca94f3c4)
