### ISSUE TITLE
Home directory adoption ~ auto identification of working directories

### ISSUE THREAD

**Issue by KABILANSRK** [Philotheephilix/Multi-funtional-telegram-bot#3]
Main python code contains the path for the directories needed pre-defined to authors PC structure 
user using this code needs to change working directory in the python code itself which is time consuming and not ideal for users with less knowledge in python

## THE FIX:
using **os module** in python the path of the current working directory can be created and can be used wherever needed

**Comment by Philotheephilix** [comment]
Closed in branch v1
